languageCode = "en-us"
title = "Andrea & James"
baseURL = "https://www.argjam.com/"
theme = "twenty"
disableKinds = ["taxonomy","taxonomyTerm"]

[params]
  googleAnalytics= "UA-110881712-1"
  copyright = "Andrea Gammon and James Meakin"
  subtitle = "Are getting married!"
  description = "**Are celebrating their wedding!**\n\n**-**\n\n**Saturday, 14 July 2018**\n\n**-**\n\n**Rising Tide**\n\n**Portland, ME**\n\n**USA**"
  tellMeMoreButton = ""
  cleanLook = true
  blurb = "Andrea (an American) met James (a Brit) in the Netherlands. This makes our wedding and reception plans a little unusual. You’re invited to celebrate with us in Portland, Maine!"

[params.social]
  github = "https://github.com/jmsmkn"
  instagram = "https://instagram.com/andrea.gammon"

